### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RajaVamsi11**
Fixed minor grammatical issue

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]

**Comment by Amejia481** [comment]
Thanks @RajaVamsi11 !

**Comment by Amejia481** [comment]
Thanks @RajaVamsi11 !

**Comment by Amejia481** [comment]
Thanks @RajaVamsi11 !

**Comment by Amejia481** [comment]
Thanks @RajaVamsi11 !

**Review by 7koma95 — APPROVED** [review]

**Pull request merged**
